complete sgt challenge
NolanReda/c0522-code-solutions pull request #103
Opened 2022-07-09 21:39 UTC by NolanReda

![stg2](https://user-images.githubusercontent.com/99226300/178123514-13accc59-755f-4325-8fa5-8d4bf3751e39.jpg)
![stg1](https://user-images.githubusercontent.com/99226300/178123515-f5e7cd24-af40-4c19-9e29-e0b633bb6958.jpg)
![stg6](https://user-images.githubusercontent.com/99226300/178123516-f6fd7342-9720-4e6b-9c7f-2ec2b4b6aff3.jpg)
![stg5](https://user-images.githubusercontent.com/99226300/178123517-e0c4ae6f-c797-4bbc-a97f-ca0010ae6beb.jpg)
![stg4](https://user-images.githubusercontent.com/99226300/178123518-828cda60-7f96-4b1b-8fea-1b1a74446b0b.jpg)
![stg3](https://user-images.githubusercontent.com/99226300/178123519-f35cbe23-ff26-45f5-8a49-df6113b60040.jpg)

2022-07-11 17:36 UTC, thebearingedge approved these changes
Each of your PUT and DELETE routes needs a `returning *` in the sql so you can decide whether or not to send a 404 after querying the database.

2022-07-11 17:36 UTC, thebearingedge requested changes
Each of your PUT and DELETE routes needs a `returning *` in the sql so you can decide whether or not to send a 404 after querying the database.

2022-08-22 23:57 UTC, NolanReda commented
All gucci, that's the end of my assignments!

2022-08-23 00:48 UTC, thebearingedge approved these changes

2022-08-23 17:13 UTC, merged