completed validated input
NolanReda/c0522-code-solutions pull request #125
Opened 2022-07-17 01:27 UTC by NolanReda

![validated input](https://user-images.githubusercontent.com/99226300/179380126-1423a1ae-a68f-42c4-b310-fa248d94c163.gif)

2022-07-18 17:50 UTC, thebearingedge requested changes

2022-07-18 17:50 UTC, thebearingedge commented on react-validated-input-component/src/validated-input.jsx
> +    }
The validation status should update as the user types and not on submit.

2022-07-22 20:24 UTC, NolanReda commented
ready for review

2022-07-22 21:47 UTC, thebearingedge approved these changes

2022-07-22 22:09 UTC, merged