completed big-o-notation
NolanReda/c0522-code-solutions pull request #138
Opened 2022-08-09 04:42 UTC by NolanReda

![image](https://user-images.githubusercontent.com/99226300/183565842-b0c585df-9ae3-441f-ae3b-75e1e6353aa7.png)

2022-08-09 16:54 UTC, thebearingedge requested changes

2022-08-09 16:54 UTC, thebearingedge commented on big-o-notation/big-o.js
> +      }
Because this section of the algorithm is within a nested loop, each of these operations are O(n^2) worst case

2022-08-10 00:11 UTC, NolanReda commented
![image](https://user-images.githubusercontent.com/99226300/183782885-898f2aa0-0bf2-45c4-bab7-08878c30d7e4.png)

2022-08-10 00:14 UTC, thebearingedge approved these changes

2022-08-10 00:15 UTC, merged