completed three column challenge
NolanReda/c0522-code-solutions pull request #18
Opened 2022-05-13 16:44 UTC by NolanReda

![three column](https://user-images.githubusercontent.com/99226300/168329440-5326c147-652f-4924-9177-6a694537bbc2.jpg)

2022-05-13 18:16 UTC, codingcodymiller requested changes
Hey Nolan! A couple notes:
1. There is too much vertical space between the images and the headline beneath it
2. The text in each column is too close to the text in the adjacent columns

Please revise and submit a new screenshot with your revision

2022-05-13 20:18 UTC, NolanReda commented
![three column](https://user-images.githubusercontent.com/99226300/168383432-05db9af4-a06d-4248-bb06-5265893f50a3.jpg)

2022-05-14 22:41 UTC, codingcodymiller requested changes

2022-05-14 22:41 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +  align-items: center;
This isn't a flexbox, so these aren't doing anything. If you add `display: flex` to this rule, they will have an effect, and you will be able to remove the margin from your `img` elements.

2022-05-14 23:14 UTC, NolanReda commented
![three column](https://user-images.githubusercontent.com/99226300/168450974-83a78225-b7a6-46d2-b109-dfcc04143fe3.jpg)

2022-05-14 23:18 UTC, codingcodymiller approved these changes
Nice work!!

2022-05-14 23:22 UTC, merged